apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: releases
  namespace: monitc
  labels:
    app.kubernetes.io/name: releases
    app.kubernetes.io/part-of: monitc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups
  namespace: monitc
  labels:
    app.kubernetes.io/name: backups
    app.kubernetes.io/part-of: monitc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
